dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: tjL8647Uyjg71OHNXMkBanT0LGZDj1MiIoY8MttResWdb40L7vouAEb9GeX88QH4C91hzGXK+j9+NjaSOBUOpSB980qgCB0gk3Vt1sKQ6LUGkroQj5ib/zXWNmFArLNevzB0uAME6lGo/rUNoFyabCkDwgpHbLSwRYbstu7HM9hqxWo3S/WbQZQMrsQRvq9qLzQFFMzjFGLozVqRnenM5Yy5rNxcw7irAjpoRFQAiXFCJ8vsWgyQ0esPIi0eHtwxHtE10CqVNUoXMx9GKLrG9WsSCDdxM+7paB7QfrwUtAuFeLK/5oMTq05vi2//9uTMGoFlTm4BZabEUO9KgAsn8AaQU3jYFIGjmVLqNcTysNLzGo39nzqEUoHm7QKt+poz4oxw+Q0ItcqnQySgvAvWHUVuvoT4jkDJJLj4f0Kjegv4YqhBL1w0yt7VtJQcr4k75AIaaE1iGtgDH9k60ayBUxErfP99Cs10IsQ8DfmXA4ozZiEtOh7yYymh9HokYhG7Bupxv/XycfmdLsBjfkOZPXccnneojMlfKqRFjPlptm6UbqILF3g3CSSqrVXMteGMqBUxX2pnSBLtDM+CfZK8ALNV3JRHYORDNeq7f1G9zbWFFbj6UKy0QwiBe/ClEabl4BeAY5OXiCndZjz25L2Hx4bkMPfZQAcnlQa5OW/krzw=
