dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: kLZ1cqdnEdvBXFSxsjz0/1sOwQ/nkUaIMErRvhQVaBQMqIWsmPDsljbx7Zs2Egb5FuYh+35cGirK154i8K9i6HZ4ftmh/hkdo+4kOwRkqaU5mCaWYu/E/0r7M834NflUmxbRkYx5bwYsLSG+xWiXSlxykB+fM/RH8CEvmZo4pjlVAiZnrRiCcHKSpPkOq0DAesSZobwuBGsdOYoMN0nWsBXz0/pSZQsJ3o/7SUyr13Psn/toDqIF1wt7ckM1ldKSHzgjdpaeA032lGPV1HrP4UTKpOvNYOtgszdjCXzUj+5bgFvIGnNqbrRtALE4iZ/Id90oEo4w9qG3bWta8dKSaph6iZY5VTDpvkiyO/79QOa8j53Vd7L8paHQEDjspMe818WbtIOjrA1KtSLNIMtSlHkPsUxwcHH3rP39syRXFIBf1btZuLD+lmEStGozOMxURwURW1OcoaGmuwvQB1yn5LbDEYoPnxgNc2Xyztw/tuqLiYtNJDAg6Yg/Koqq+L5GVxdV/NRYtcbteLoBFru3kPazxkkO/rvtNZ4xqhrxDec+KLYGV5U63quzXb5dfAO+qy5yXURDlGvBmZ2oH08c80vUp6OmKqll4TUVOCNdEmmAJQYuOJWoqB8VWj+ovtGrJJhfvbApglmSCc6H3Y1i7/darW1JeVdg13idUWDGuqw=
