- name: Configure App
  hosts: app
  become: true
#  vars:
#   db_host:  104.155.6.94

  roles:
    - role: app

    - role: jdauphant.nginx
      nginx_sites:
        default:
          - listen 80
          - server_name "reddit"
          - location / {
            proxy_pass http://127.0.0.1:9292;
            }
